### PR TITLE
Tl article card

### PR DESCRIPTION
**Pull request by TarynL**
Description
Added Article card with submit form including edit and delete

Type of change
 [x] New feature (non-breaking change which adds functionality)

Testing Instructions
Check article tab for article list. Test edit button and delete button

 Checklist:
 [x ] My code follows the style guidelines of this project
 [x ] I have performed a self-review of my own code
 [ ] I have commented my code, particularly in hard-to-understand areas
 [x] My changes generate no new warnings or errors
 [x ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by LaurelMorrison — CHANGES_REQUESTED** [review]
Looks great! Only comment is that we need to change one of the ids in the data to not match.

**Review by D-Upchurch — APPROVED** [review]
Looks good!

**Review by LaurelMorrison — APPROVED** [review]
Yay! Looks good

**Review by TarynL — COMMENTED** [review]
Just fixed

**Pull request merged**
